name: selenium test tun demo with github actions
run-name: ${{ github.actor }} is testing out GitHub Actions for selenium tests
on:
  push:
    paths-ignore:
      - '.github/**'
      - '.idea'
      - 'target'

jobs:
  run selenium tests:
    steps:
      - runs-on: ubuntu-latest
      - run: echo ls ${{ github.workspace }}
      - run: mvn clean test -Dsurefire.suiteXmlFiles="src/main/java/org/sele/git/testng.xml"
